# Generated by Django 5.2 on 2025-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_name'], name='core_order_client__3038eb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone'], name='core_order_phone_582566_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['comment'], name='core_order_comment_e18a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client_name', 'phone', 'comment'], name='name_phone_comment_index'),
        ),
    ]
