# Generated by Django 5.2 on 2025-06-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_review_is_published_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
